# fly.toml app configuration file generated for the-switch-platform on 2026-06-22T01:42:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-switch-platform'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOSTNAME = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3000'
  SWITCH_AUTO_BOOTSTRAP_SQLITE = '1'
  SWITCH_CMS_BACKEND_MODE = 'live'
  SWITCH_DATA_DIRECTORY = '/data'
  SWITCH_PERSISTENCE_DRIVER = 'sqlite'

[[mounts]]
  source = 'switch_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
