import type { AccessibilitySnapshot } from "@/modules/accessibility/types";
import type { DashboardHomeData } from "@/modules/dashboard/types";

export function buildMockPreviewAccessibilitySnapshot(userId: string): AccessibilitySnapshot {
  return {
    settings: {
      userId,
      preferences: {
        focusModeEnabled: false,
        dyslexiaFriendlyFontEnabled: false,
        lineSpacing: "default",
        reducedDistractionModeEnabled: false,
        colouredOverlay: "default",
        highContrastModeEnabled: false,
        largePrintEnabled: false,
      },
      preferredReadingSpeed: 1,
      preferredFontSize: 18,
      preferredColourScheme: "default",
      focusModeEnabled: false,
      highContrastModeEnabled: false,
      dyslexiaFriendlyFontEnabled: false,
      reducedDistractionModeEnabled: false,
      lineSpacing: "default",
      textToSpeechEnabled: false,
    },
    studentAccessProfile: {
      userId,
      activeAccessArrangements: [],
      preferredReadingSpeed: 1,
      preferredFontSize: 18,
      preferredColourScheme: "default",
      textToSpeechEnabled: false,
      accessibilityPreferences: {
        focusModeEnabled: false,
        dyslexiaFriendlyFontEnabled: false,
        lineSpacing: "default",
        reducedDistractionModeEnabled: false,
        colouredOverlay: "default",
        highContrastModeEnabled: false,
        largePrintEnabled: false,
      },
    },
  };
}

export function buildMockPreviewDashboardData(): DashboardHomeData {
  return {
    summary: {
      dataState: "ready",
      overallLevel: "Current Flow",
      overallTrend: "improving",
      examReadinessScore: 68,
      completedSessionCount: 12,
      activeSessionCount: 3,
      trackedSubjectCount: 4,
      subjectsNeedingAttentionCount: 2,
      accessSnapshotCoverage: 100,
      latestActivityAt: new Date().toISOString(),
      resumeHref: "/dashboard",
      nextBestAction: "Return to English Language analysis practice.",
      nextBestActionHref: "/assessments",
      sourceWarnings: [],
      subjectProgress: [
        {
          subject: "English Language",
          subjectId: "gcse-english-language",
          level: "Voltage Rising",
          trend: "improving",
          readinessScore: 71,
          completionScore: 62,
          activeSessionCount: 1,
          completedSessionCount: 4,
          reviewItemCount: 1,
          accessSnapshotCount: 3,
          recommendedFocus: "Question structure and evidence selection.",
          evidence: "Recent checkpoint gains and one saved exam review.",
          subjectHref: "/subjects",
          resumeHref: "/assessments",
        },
        {
          subject: "Mathematics",
          subjectId: "gcse-maths",
          level: "Current Flow",
          trend: "stable",
          readinessScore: 66,
          completionScore: 58,
          activeSessionCount: 1,
          completedSessionCount: 5,
          reviewItemCount: 2,
          accessSnapshotCount: 2,
          recommendedFocus: "Algebra rearranging and ratio fluency.",
          evidence: "Mixed paper performance with a few repeat slips.",
          subjectHref: "/subjects",
          resumeHref: "/exams",
        },
        {
          subject: "Combined Science",
          subjectId: "gcse-combined-science",
          level: "Powered Up",
          trend: "improving",
          readinessScore: 59,
          completionScore: 51,
          activeSessionCount: 1,
          completedSessionCount: 3,
          reviewItemCount: 1,
          accessSnapshotCount: 1,
          recommendedFocus: "Energy transfers and practical method recall.",
          evidence: "Strong restart momentum after two shorter checkpoints.",
          subjectHref: "/subjects",
          resumeHref: "/assessments",
        },
      ],
    },
    metrics: [
      {
        label: "Readiness",
        value: "68 / 100",
        detail: "A calmer overview of current exam readiness.",
        tone: "teal",
      },
      {
        label: "Live sessions",
        value: "3",
        detail: "One resume card should be enough above the fold.",
        tone: "emerald",
      },
      {
        label: "Subjects",
        value: "4",
        detail: "Keep only the strongest focus signals visible.",
        tone: "amber",
      },
      {
        label: "Support",
        value: "Ready",
        detail: "Accessibility and support stay available without crowding the page.",
        tone: "sky",
      },
    ],
    dailyMotivation: {
      quote: "One focused step today can make tomorrow feel much lighter.",
      reflection: "The streamlined version should make the next study step feel obvious.",
      focusLabel: "Lower tomorrow's pressure",
      colour: "teal",
    },
    routeCards: [
      {
        href: "/dashboard",
        eyebrow: "Student home",
        title: "Open your study home",
        description: "See one clear next step, not a packed wall of competing cards.",
        stat: "Recommended now",
        tone: "teal",
      },
      {
        href: "/progress",
        eyebrow: "Planner",
        title: "Follow the weekly plan",
        description: "Bring progress, exams, and saved work into one simpler planning view.",
        stat: "7-day overview",
        tone: "sky",
      },
      {
        href: "/accessibility",
        eyebrow: "Access",
        title: "Adjust support settings",
        description: "Keep SEND and accessibility close, but grouped into one support area.",
        stat: "Access ready",
        tone: "amber",
      },
    ],
    examSessions: [
      {
        sessionId: "mock-exam-1",
        href: "/exams",
        kind: "exam",
        status: "in-progress",
        title: "Maths Paper 1",
        subtitle: "AQA Higher • resume available",
        completionPercentage: 64,
        timeLabel: "42 mins remaining",
        statusLabel: "2 flagged questions",
        supportLabel: "Support-ready through access profile layer",
        supportPreferenceChips: ["Accessibility setup"],
        focusLabel: "Algebra accuracy",
        reviewCount: 2,
        actionLabel: "Resume paper",
      },
    ],
    assessmentSessions: [
      {
        sessionId: "mock-assessment-1",
        href: "/assessments",
        kind: "assessment",
        status: "in-progress",
        title: "English analysis checkpoint",
        subtitle: "GCSE English Language • 20 min cap",
        completionPercentage: 50,
        timeLabel: "10 mins remaining",
        statusLabel: "Checkpoint in progress",
        supportLabel: "Accessibility settings available",
        supportPreferenceChips: ["Accessibility setup", "SEND support signposting"],
        focusLabel: "Evidence selection",
        reviewCount: 0,
        actionLabel: "Resume checkpoint",
      },
    ],
    focusCards: [
      {
        subject: "English Language",
        subjectId: "gcse-english-language",
        tone: "teal",
        level: "Voltage Rising",
        trend: "improving",
        readinessScore: 71,
        recommendedFocus: "Tighten response structure and annotation choices.",
        evidence: "Recent checkpoint progress",
      },
      {
        subject: "Mathematics",
        subjectId: "gcse-maths",
        tone: "sky",
        level: "Current Flow",
        trend: "stable",
        readinessScore: 66,
        recommendedFocus: "Return to ratio and rearranging formulas.",
        evidence: "One exam session and one submitted review",
      },
      {
        subject: "Combined Science",
        subjectId: "gcse-combined-science",
        tone: "amber",
        level: "Powered Up",
        trend: "improving",
        readinessScore: 59,
        recommendedFocus: "Energy stores and practical methods.",
        evidence: "Checkpoint restart trend",
      },
    ],
    strongestSubject: {
      subject: "English Language",
      subjectId: "gcse-english-language",
      tone: "teal",
      level: "Voltage Rising",
      trend: "improving",
      readinessScore: 71,
      recommendedFocus: "Keep building paragraph control.",
      evidence: "Strongest current route",
    },
    weakestSubject: {
      subject: "Combined Science",
      subjectId: "gcse-combined-science",
      tone: "amber",
      level: "Powered Up",
      trend: "improving",
      readinessScore: 59,
      recommendedFocus: "Make science the next short session.",
      evidence: "Most fragile current route",
    },
    recommendedAction: "Return to English Language analysis practice.",
    continuityStatus: "resume-active-session",
    continuityDescription: "One active session is enough to keep momentum without adding more dashboard noise.",
    continuityHref: "/assessments",
    continuityActionLabel: "Continue checkpoint",
    supportSnapshotSummary: "Onboarding support choices should sit in one grouped rail rather than being repeated across the page.",
    supportPreferenceChips: ["Accessibility setup", "SEND support signposting"],
    plannerPromptDismissed: false,
    weeklyPlanner: {
      weekLabel: "This week",
      dataSourceSummary: "Preview-only planner data",
      days: [
        {
          dayKey: "mon",
          weekdayLabel: "Mon",
          isToday: true,
          items: [
            {
              itemId: "item-1",
              kind: "recommended",
              subject: "English Language",
              subjectId: "gcse-english-language",
              tone: "teal",
              title: "20-minute analysis checkpoint",
              subtitle: "Resume the most relevant active practice",
              href: "/assessments",
              status: "recommended",
              sourceLabel: "Recommended now",
            },
          ],
        },
        {
          dayKey: "wed",
          weekdayLabel: "Wed",
          isToday: false,
          items: [
            {
              itemId: "item-2",
              kind: "exam",
              subject: "Mathematics",
              subjectId: "gcse-maths",
              tone: "sky",
              title: "Resume Paper 1",
              subtitle: "Keep one deeper exam block in the week",
              href: "/exams",
              status: "scheduled",
              sourceLabel: "Saved progress",
            },
          ],
        },
        {
          dayKey: "fri",
          weekdayLabel: "Fri",
          isToday: false,
          items: [
            {
              itemId: "item-3",
              kind: "assessment",
              subject: "Combined Science",
              subjectId: "gcse-combined-science",
              tone: "amber",
              title: "Practical methods checkpoint",
              subtitle: "Shorter end-of-week refresh",
              href: "/assessments",
              status: "scheduled",
              sourceLabel: "Planner suggestion",
            },
          ],
        },
      ],
    },
  };
}
