import type { ExamPaperBlueprint } from "./paper-blueprint-types";
export const seededCombinedSciencePaperBlueprints: ExamPaperBlueprint[] = [
  {
    examId: "aqa-combined-science-paper-1",
    title: "GCSE Combined Science",
    subject: "Combined Science",
    paperMode: "full-gcse",
    studentStage: "gcse",
    board: "AQA",
    qualificationType: "GCSE",
    tier: "FOUNDATION",
    paperName: "Paper 1",
    year: 2025,
    durationMinutes: 70,
    totalMarks: 60,
    yearGroups: ["Year 10", "Year 11"],
    curriculumTags: ["Year 11 mock readiness", "Biology chemistry physics mix", "GCSE trilogy paper fluency"],
    boardTopicCoverage:
      "Built around common AQA GCSE Combined Science: Trilogy Paper 1 expectations across cell biology, atomic structure, and electricity.",
    accessSupportLevel: "send-ready-foundation",
    sourceProviderId: "seed-exam-engine",
    skillsFocus: ["Cell Biology", "Atomic Structure", "Electricity"],
    studentContextSummary:
      "Full GCSE Combined Science paper practice covering biology, chemistry, and physics in one timed session.",
    gcsePreparationSummary:
      "Use after topic revision in Combined Science so students can move from checkpoints into full-paper timing.",
    questionSlots: [
      {
        slotId: "q1",
        number: 1,
        topic: "Cell Biology",
        marks: 2,
        type: "multiple-choice",
        guidance: "Recall which structures are found in plant cells but not in animal cells.",
        variants: [
          {
            questionId: "q1-v1",
            number: 1,
            topic: "Cell Biology",
            prompt: "Which structure is found in a plant cell but not in an animal cell?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Nucleus" },
              { optionId: "b", label: "B", text: "Cell membrane" },
              { optionId: "c", label: "C", text: "Chloroplast" },
              { optionId: "d", label: "D", text: "Cytoplasm" },
            ],
            correctOptionId: "c",
            sourceQuestionKey: "aqa-combined-science-paper-1-q1-v1",
          },
          {
            questionId: "q1-v2",
            number: 1,
            topic: "Cell Biology",
            prompt: "Which part of the cell controls the activities of the cell?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Ribosome" },
              { optionId: "b", label: "B", text: "Nucleus" },
              { optionId: "c", label: "C", text: "Cell wall" },
              { optionId: "d", label: "D", text: "Vacuole" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "aqa-combined-science-paper-1-q1-v2",
          },
        ],
      },
      {
        slotId: "q2",
        number: 2,
        topic: "Atomic Structure",
        marks: 2,
        type: "multiple-choice",
        guidance: "Use the periodic table: elements in the same group have similar properties.",
        variants: [
          {
            questionId: "q2-v1",
            number: 2,
            topic: "Atomic Structure",
            prompt: "An atom of sodium has 11 protons. How many electrons does a neutral sodium atom have?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "10" },
              { optionId: "b", label: "B", text: "11" },
              { optionId: "c", label: "C", text: "12" },
              { optionId: "d", label: "D", text: "23" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "aqa-combined-science-paper-1-q2-v1",
          },
          {
            questionId: "q2-v2",
            number: 2,
            topic: "Atomic Structure",
            prompt: "Which subatomic particle has a negative charge?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Proton" },
              { optionId: "b", label: "B", text: "Neutron" },
              { optionId: "c", label: "C", text: "Electron" },
              { optionId: "d", label: "D", text: "Nucleus" },
            ],
            correctOptionId: "c",
            sourceQuestionKey: "aqa-combined-science-paper-1-q2-v2",
          },
        ],
      },
      {
        slotId: "q3",
        number: 3,
        topic: "Electricity",
        marks: 3,
        type: "multiple-choice",
        guidance: "In a series circuit, current is the same at every point.",
        variants: [
          {
            questionId: "q3-v1",
            number: 3,
            topic: "Electricity",
            prompt:
              "Two identical lamps are connected in series to a battery. Which statement is correct?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "The current is greater through the first lamp." },
              { optionId: "b", label: "B", text: "The current is the same through both lamps." },
              { optionId: "c", label: "C", text: "The voltage is the same across each lamp." },
              { optionId: "d", label: "D", text: "If one lamp breaks, the other stays bright." },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "aqa-combined-science-paper-1-q3-v1",
          },
          {
            questionId: "q3-v2",
            number: 3,
            topic: "Electricity",
            prompt: "Which unit is used to measure electric current?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Volt (V)" },
              { optionId: "b", label: "B", text: "Ohm (Ω)" },
              { optionId: "c", label: "C", text: "Amp (A)" },
              { optionId: "d", label: "D", text: "Joule (J)" },
            ],
            correctOptionId: "c",
            sourceQuestionKey: "aqa-combined-science-paper-1-q3-v2",
          },
        ],
      },
      {
        slotId: "q4",
        number: 4,
        topic: "Energy Stores",
        marks: 3,
        type: "multiple-choice",
        guidance: "Energy is transferred when work is done or when heating occurs.",
        variants: [
          {
            questionId: "q4-v1",
            number: 4,
            topic: "Energy Stores",
            prompt:
              "A student lifts a book onto a shelf. Which energy store in the book increases?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Thermal store" },
              { optionId: "b", label: "B", text: "Gravitational potential store" },
              { optionId: "c", label: "C", text: "Chemical store" },
              { optionId: "d", label: "D", text: "Kinetic store" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "aqa-combined-science-paper-1-q4-v1",
          },
          {
            questionId: "q4-v2",
            number: 4,
            topic: "Energy Stores",
            prompt: "In a food chain, where does the energy in producers originally come from?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Soil minerals" },
              { optionId: "b", label: "B", text: "Sunlight" },
              { optionId: "c", label: "C", text: "Consumers" },
              { optionId: "d", label: "D", text: "Decomposers" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "aqa-combined-science-paper-1-q4-v2",
          },
        ],
      },
    ],
  },
  {
    examId: "edexcel-combined-science-paper-1",
    title: "GCSE Combined Science",
    subject: "Combined Science",
    paperMode: "full-gcse",
    studentStage: "gcse",
    board: "Edexcel",
    qualificationType: "GCSE",
    tier: "FOUNDATION",
    paperName: "Paper 1",
    year: 2025,
    durationMinutes: 70,
    totalMarks: 60,
    yearGroups: ["Year 10", "Year 11"],
    curriculumTags: ["Year 11 mock readiness", "Biology chemistry physics mix", "GCSE paper fluency"],
    boardTopicCoverage:
      "Built around shared Edexcel GCSE Combined Science Paper 1 habits across health, particles, and forces.",
    accessSupportLevel: "send-ready-foundation",
    sourceProviderId: "seed-exam-engine",
    skillsFocus: ["Health and Disease", "Particle Model", "Forces"],
    studentContextSummary:
      "Full GCSE Combined Science paper practice for Edexcel routes with biology, chemistry, and physics questions.",
    gcsePreparationSummary:
      "Use once Combined Science topic checkpoints feel secure and the student is ready for full paper timing.",
    questionSlots: [
      {
        slotId: "q1",
        number: 1,
        topic: "Health and Disease",
        marks: 2,
        type: "multiple-choice",
        variants: [
          {
            questionId: "q1-v1",
            number: 1,
            topic: "Health and Disease",
            prompt: "Which pathogen causes measles?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Bacterium" },
              { optionId: "b", label: "B", text: "Virus" },
              { optionId: "c", label: "C", text: "Fungus" },
              { optionId: "d", label: "D", text: "Protist" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q1-v1",
          },
          {
            questionId: "q1-v2",
            number: 1,
            topic: "Health and Disease",
            prompt: "Which organ system transports oxygen around the body?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Digestive system" },
              { optionId: "b", label: "B", text: "Circulatory system" },
              { optionId: "c", label: "C", text: "Respiratory system" },
              { optionId: "d", label: "D", text: "Nervous system" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q1-v2",
          },
        ],
      },
      {
        slotId: "q2",
        number: 2,
        topic: "Particle Model",
        marks: 2,
        type: "multiple-choice",
        variants: [
          {
            questionId: "q2-v1",
            number: 2,
            topic: "Particle Model",
            prompt: "Which state of matter has a fixed volume but no fixed shape?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Solid" },
              { optionId: "b", label: "B", text: "Liquid" },
              { optionId: "c", label: "C", text: "Gas" },
              { optionId: "d", label: "D", text: "Plasma" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q2-v1",
          },
          {
            questionId: "q2-v2",
            number: 2,
            topic: "Particle Model",
            prompt: "When a substance melts, which change happens to the particles?",
            marks: 2,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "They move closer together." },
              { optionId: "b", label: "B", text: "They gain energy and move more." },
              { optionId: "c", label: "C", text: "They stop moving completely." },
              { optionId: "d", label: "D", text: "They break into atoms only." },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q2-v2",
          },
        ],
      },
      {
        slotId: "q3",
        number: 3,
        topic: "Forces",
        marks: 3,
        type: "multiple-choice",
        variants: [
          {
            questionId: "q3-v1",
            number: 3,
            topic: "Forces",
            prompt: "A box rests on a table. Which force balances the weight of the box?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Air resistance" },
              { optionId: "b", label: "B", text: "Contact force from the table" },
              { optionId: "c", label: "C", text: "Friction from the floor" },
              { optionId: "d", label: "D", text: "Magnetic force" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q3-v1",
          },
          {
            questionId: "q3-v2",
            number: 3,
            topic: "Forces",
            prompt: "Which unit is used to measure force?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Joule (J)" },
              { optionId: "b", label: "B", text: "Watt (W)" },
              { optionId: "c", label: "C", text: "Newton (N)" },
              { optionId: "d", label: "D", text: "Pascal (Pa)" },
            ],
            correctOptionId: "c",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q3-v2",
          },
        ],
      },
      {
        slotId: "q4",
        number: 4,
        topic: "Ecology",
        marks: 3,
        type: "multiple-choice",
        variants: [
          {
            questionId: "q4-v1",
            number: 4,
            topic: "Ecology",
            prompt: "Which process removes carbon dioxide from the atmosphere?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Respiration" },
              { optionId: "b", label: "B", text: "Photosynthesis" },
              { optionId: "c", label: "C", text: "Combustion" },
              { optionId: "d", label: "D", text: "Decomposition" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q4-v1",
          },
          {
            questionId: "q4-v2",
            number: 4,
            topic: "Ecology",
            prompt: "Which term describes all the organisms of one species living in an area?",
            marks: 3,
            type: "multiple-choice",
            options: [
              { optionId: "a", label: "A", text: "Community" },
              { optionId: "b", label: "B", text: "Population" },
              { optionId: "c", label: "C", text: "Ecosystem" },
              { optionId: "d", label: "D", text: "Habitat" },
            ],
            correctOptionId: "b",
            sourceQuestionKey: "edexcel-combined-science-paper-1-q4-v2",
          },
        ],
      },
    ],
  },
];
