import type { StudentAccessProfile } from "@/modules/access-arrangements";
import type { AccessibilitySnapshot } from "@/modules/accessibility/types";
import type { MvpCatalogSubject } from "@/modules/content/types";
import type { DashboardHomeData } from "@/modules/dashboard/types";
import type { PowerGridSummary } from "@/modules/power-grid/types";
import type { Recommendation } from "@/modules/recommendations/types";
import type { ReadAloudSession } from "@/modules/read-aloud/types";
import type { SupportHubData } from "@/modules/support/types";

export const basePowerGridSummary: PowerGridSummary = {
  dataState: "ready",
  overallLevel: "Voltage Rising",
  overallTrend: "improving",
  examReadinessScore: 68,
  completedSessionCount: 14,
  activeSessionCount: 3,
  quizAttemptCount: 9,
  quizCorrectCount: 6,
  quizAccuracyPercentage: 67,
  xpTotal: 248,
  voltagePointsTotal: 191,
  trackedSubjectCount: 3,
  subjectsNeedingAttentionCount: 1,
  accessSnapshotCoverage: 100,
  latestActivityAt: "2026-06-15T10:30:00.000Z",
  resumeHref: "/saved-progress",
  nextBestAction: "Resume algebra exam practice",
  nextBestActionHref: "/exams",
  recoveryTitle: "Resume-ready progress",
  recoveryDescription: "Saved sessions are ready to reopen across assessments and exams.",
  sourceWarnings: [],
  subjectProgress: [
    {
      subject: "GCSE Mathematics",
      subjectId: "gcse-maths",
      level: "Voltage Rising",
      trend: "improving",
      readinessScore: 72,
      completionScore: 61,
      activeSessionCount: 1,
      completedSessionCount: 6,
      quizAttemptCount: 3,
      quizCorrectCount: 2,
      quizAccuracyPercentage: 67,
      xpEarned: 92,
      voltagePoints: 142,
      reviewItemCount: 2,
      accessSnapshotCount: 3,
      recommendedFocus: "Algebra",
      recommendedTopicId: "maths-algebra",
      subjectHref: "/subjects",
      resumeHref: "/saved-progress",
      lastActivityAt: "2026-06-15T10:00:00.000Z",
      evidence: "Recent timed practice and saved-paper recovery both improved confidence.",
    },
    {
      subject: "GCSE English Language",
      subjectId: "gcse-english-language",
      level: "Current Flow",
      trend: "stable",
      readinessScore: 60,
      completionScore: 55,
      activeSessionCount: 1,
      completedSessionCount: 4,
      quizAttemptCount: 3,
      quizCorrectCount: 2,
      quizAccuracyPercentage: 67,
      xpEarned: 80,
      voltagePoints: 110,
      reviewItemCount: 1,
      accessSnapshotCount: 2,
      recommendedFocus: "Language Analysis",
      recommendedTopicId: "english-language-analysis",
      subjectHref: "/subjects",
      resumeHref: "/saved-progress",
      lastActivityAt: "2026-06-14T15:20:00.000Z",
      evidence: "Reading analysis accuracy is holding, but timing still needs work.",
    },
    {
      subject: "GCSE Combined Science",
      subjectId: "gcse-combined-science",
      level: "Powered Up",
      trend: "declining",
      readinessScore: 45,
      completionScore: 38,
      activeSessionCount: 1,
      completedSessionCount: 4,
      quizAttemptCount: 3,
      quizCorrectCount: 2,
      quizAccuracyPercentage: 67,
      xpEarned: 76,
      voltagePoints: 95,
      reviewItemCount: 3,
      accessSnapshotCount: 2,
      recommendedFocus: "Chemical Changes",
      recommendedTopicId: "science-chemical-changes",
      subjectHref: "/subjects",
      resumeHref: "/saved-progress",
      lastActivityAt: "2026-06-13T08:40:00.000Z",
      evidence: "Science explanations are slipping when questions become more applied.",
    },
  ],
};

export const baseDashboardHomeData: DashboardHomeData = {
  summary: basePowerGridSummary,
  metrics: [
    {
      label: "Readiness",
      value: "68%",
      detail: "Overall exam-readiness is climbing from recent saved work and practice.",
      tone: "teal",
    },
    {
      label: "Saved sessions",
      value: "3",
      detail: "Active sessions are ready to resume across the highest-priority routes.",
      tone: "amber",
    },
    {
      label: "Review items",
      value: "6",
      detail: "Marked review points are gathered into the dashboard instead of being lost.",
      tone: "sky",
    },
  ],
  dailyMotivation: {
    quote: "Small progress still counts, especially on the days that feel slow.",
    speaker: "Nelson Mandela",
    region: "South Africa · Africa",
    occupation: "Anti-apartheid leader and former President",
    theme: "Perseverance",
    reflection:
      "One calmer revision block, one reviewed mistake, or one restarted session still moves the learner forward.",
    focusLabel: "Keep the streak gentle",
    colour: "teal",
    learnMoreHref: "/support",
  },
  routeCards: [
    {
      href: "/exams",
      eyebrow: "Exam Engine",
      title: "Resume a full paper",
      description: "Reopen the highest-priority paper flow with saved timing and responses.",
      stat: "1 active paper",
      tone: "teal",
    },
    {
      href: "/assessments",
      eyebrow: "Timed Assessments",
      title: "Start focused practice",
      description: "Use shorter timed checks before moving back into full paper conditions.",
      stat: "3 assessment options",
      tone: "amber",
    },
    {
      href: "/saved-progress",
      eyebrow: "Saved Progress",
      title: "Review continuity",
      description: "See what is paused, resumable, or ready for review without losing context.",
      stat: "Resume-ready",
      tone: "sky",
    },
    {
      href: "/support",
      eyebrow: "Support",
      title: "Keep support visible",
      description: "Support preferences and calmer next steps stay visible alongside study work.",
      stat: "Urgent help visible",
      tone: "rose",
    },
  ],
  examSessions: [
    {
      sessionId: "exam-1",
      href: "/exams",
      kind: "exam",
      status: "in-progress",
      title: "GCSE Mathematics Paper 1",
      subtitle: "AQA Higher",
      completionPercentage: 58,
      timeLabel: "32 minutes remaining",
      statusLabel: "In progress",
      supportLabel: "Text to speech ready",
      supportPreferenceChips: ["Focus mode", "Text to speech"],
      focusLabel: "Resume algebra and ratio questions",
      reviewCount: 2,
      actionLabel: "Continue paper",
    },
  ],
  assessmentSessions: [
    {
      sessionId: "assessment-1",
      href: "/assessments",
      kind: "assessment",
      status: "submitted",
      title: "English language quick check",
      subtitle: "Language analysis",
      completionPercentage: 100,
      timeLabel: "Submitted this morning",
      statusLabel: "Ready for review",
      supportLabel: "Support profile saved",
      supportPreferenceChips: ["Reduced distraction"],
      focusLabel: "Review evidence selection",
      reviewCount: 1,
      actionLabel: "Open review",
    },
  ],
  focusCards: [
    {
      subject: "GCSE Mathematics",
      subjectId: "gcse-maths",
      tone: "teal",
      level: "Voltage Rising",
      trend: "improving",
      readinessScore: 72,
      recommendedFocus: "Algebra",
      evidence: "Saved paper recovery and recent timed practice are both lifting fluency.",
    },
    {
      subject: "GCSE Combined Science",
      subjectId: "gcse-combined-science",
      tone: "emerald",
      level: "Powered Up",
      trend: "declining",
      readinessScore: 45,
      recommendedFocus: "Chemical Changes",
      evidence: "Explanations need more structured practice before the next timed attempt.",
    },
  ],
  strongestSubject: {
    subject: "GCSE Mathematics",
    level: "Voltage Rising",
    trend: "improving",
    readinessScore: 72,
    recommendedFocus: "Algebra",
    evidence: "Momentum is strongest here right now.",
  },
  weakestSubject: {
    subject: "GCSE Combined Science",
    level: "Powered Up",
    trend: "declining",
    readinessScore: 45,
    recommendedFocus: "Chemical Changes",
    evidence: "This is the route that needs support next.",
  },
  recommendedAction: "Resume the maths paper, then review the science weak spot.",
  continuityStatus: "resume-active-session",
  continuityDescription: "The student has saved work ready to reopen immediately.",
  continuityHref: "/saved-progress",
  continuityActionLabel: "Resume saved work",
  supportSnapshotSummary:
    "Support settings, calmer pacing, and resume-ready progress now surface together instead of living in isolated routes.",
  supportPreferenceChips: ["Focus mode", "Reduced distraction", "Text to speech"],
  plannerPromptDismissed: false,
  weeklyPlanner: {
    weekLabel: "23–29 Jun 2026",
    dataSourceSummary: "Built from saved sessions and Power Grid signals.",
    days: [
      { dayKey: "2026-06-23", weekdayLabel: "Mon", isToday: true, items: [] },
      { dayKey: "2026-06-24", weekdayLabel: "Tue", isToday: false, items: [] },
      { dayKey: "2026-06-25", weekdayLabel: "Wed", isToday: false, items: [] },
      { dayKey: "2026-06-26", weekdayLabel: "Thu", isToday: false, items: [] },
      { dayKey: "2026-06-27", weekdayLabel: "Fri", isToday: false, items: [] },
      { dayKey: "2026-06-28", weekdayLabel: "Sat", isToday: false, items: [] },
      { dayKey: "2026-06-29", weekdayLabel: "Sun", isToday: false, items: [] },
    ],
  },
  onboardingPersonalization: {
    isActive: false,
    subjectFilterIds: [],
    qualificationLabel: "GCSE",
    examBoard: null,
    studyGoalLabel: "",
    studyGoalMessage: "Complete onboarding to personalise your dashboard.",
    setupSummary: "Complete onboarding to personalise your dashboard.",
    primarySubjectId: null,
    primarySubjectHref: "/subjects",
    examAvailabilitySummary: "",
  },
};
export const baseSubjects: MvpCatalogSubject[] = [
  {
    subjectId: "gcse-maths",
    name: "GCSE Mathematics",
    qualificationType: "GCSE",
    examBoards: ["AQA", "Edexcel", "OCR"],
    description: "Core number, algebra, geometry, ratio, and statistics revision.",
    topicCount: 3,
    revisionResourceCount: 12,
    examReadinessScore: 56,
    nextTopicToRevise: "Algebra",
    studentStudyStage: "year-10-end-of-year",
    endOfYearExamContext:
      "Built for Year 10 students preparing for end-of-year internal exams with GCSE-style expectations.",
    gcsePreparationGoal:
      "Move students from Year 10 end-of-year confidence into stronger GCSE paper readiness.",
    yearGroups: ["Year 10", "Year 11"],
    boardCoverageNote:
      "Maths coverage is shaped around common AQA, Edexcel, and OCR sequencing.",
  },
  {
    subjectId: "gcse-english-language",
    name: "GCSE English Language",
    qualificationType: "GCSE",
    examBoards: ["Edexcel", "AQA", "Eduqas"],
    description: "Reading, inference, language analysis, structure, and writing craft.",
    topicCount: 3,
    revisionResourceCount: 12,
    examReadinessScore: 61,
    nextTopicToRevise: "Language Analysis",
    studentStudyStage: "year-10-end-of-year",
    endOfYearExamContext:
      "Built for Year 10 students bridging into GCSE extract work and analytical writing.",
    gcsePreparationGoal:
      "Prepare students for GCSE English Language expectations before Year 11 pressure rises.",
    yearGroups: ["Year 10", "Year 11"],
    boardCoverageNote:
      "English coverage follows shared Year 10 and Year 11 reading-analysis expectations.",
  },
  {
    subjectId: "gcse-combined-science",
    name: "GCSE Combined Science",
    qualificationType: "GCSE",
    examBoards: ["AQA", "Edexcel", "OCR"],
    description: "Biology, chemistry, and physics through exam-ready checkpoints.",
    topicCount: 3,
    revisionResourceCount: 12,
    examReadinessScore: 47,
    nextTopicToRevise: "Chemical Changes",
    studentStudyStage: "year-10-end-of-year",
    endOfYearExamContext:
      "Built for Year 10 end-of-year science exams with increasing GCSE-style application work.",
    gcsePreparationGoal:
      "Use Year 10 science revision to make the jump into GCSE-style practical and explanation questions feel familiar.",
    yearGroups: ["Year 10", "Year 11"],
    boardCoverageNote:
      "Science coverage is organised around foundations and application work common across launch boards.",
  },
];

export const baseAccessibilitySnapshot: AccessibilitySnapshot = {
  settings: {
    userId: "student-demo",
    preferences: {
      focusModeEnabled: true,
      reducedDistractionModeEnabled: true,
      lineSpacing: "wide",
      highContrastModeEnabled: false,
      dyslexiaFriendlyFontEnabled: false,
    },
    preferredReadingSpeed: 1.1,
    preferredFontSize: 18,
    preferredColourScheme: "default",
    focusModeEnabled: true,
    highContrastModeEnabled: false,
    dyslexiaFriendlyFontEnabled: false,
    reducedDistractionModeEnabled: true,
    lineSpacing: "wide",
    textToSpeechEnabled: true,
  },
  studentAccessProfile: {
    userId: "student-demo",
    activeAccessArrangements: ["READER", "TEXT_TO_SPEECH"],
    preferredReadingSpeed: 1.1,
    preferredFontSize: 18,
    preferredColourScheme: "default",
    textToSpeechEnabled: true,
    accessibilityPreferences: {
      focusModeEnabled: true,
      reducedDistractionModeEnabled: true,
      lineSpacing: "wide",
      highContrastModeEnabled: false,
      dyslexiaFriendlyFontEnabled: false,
    },
  } satisfies StudentAccessProfile,
};

export const baseReadAloudSession: ReadAloudSession = {
  sessionId: "read-aloud-preview",
  userId: "student-demo",
  contentType: "recommendation",
  previewText:
    "Resume the maths paper first, then take a calmer review pass through the science explanation questions.",
  selectedVoiceId: "voice-en-gb-1",
  speed: 1.1,
  availableVoices: [
    { voiceId: "voice-en-gb-1", label: "Guide voice", language: "en-GB" },
    { voiceId: "voice-en-gb-2", label: "Calm voice", language: "en-GB" },
  ],
};

export const baseRecommendations: Recommendation[] = [
  {
    recommendationId: "rec-1",
    userId: "student-demo",
    category: "resume-saved",
    eyebrow: "Resume saved work",
    title: "Continue the active maths paper",
    description: "The learner already has strong context in this session, so the fastest win is to reopen it.",
    actionLabel: "Resume paper",
    href: "/exams",
    priority: "high",
  },
  {
    recommendationId: "rec-2",
    userId: "student-demo",
    category: "access-support",
    eyebrow: "Support carry-over",
    title: "Keep reduced-distraction settings active",
    description: "Preserve the same calmer layout before the next science review pass.",
    actionLabel: "Review settings",
    href: "/accessibility",
    priority: "medium",
  },
];

export const baseSupportHubData: SupportHubData = {
  title: "Support Hub",
  description: "Trusted signposting for young people under study pressure.",
  safetyNotice: "This route offers signposting, not counselling or crisis intervention.",
  safetyReview: {
    reviewedAt: "2026-06-10T09:00:00.000Z",
    reviewedBy: "Support editor",
    audience: "young-people",
    policySummary: "Urgent help stays visible and the route avoids therapeutic claims.",
    escalationGuidance: "If the student needs urgent help, show urgent-help routes clearly and immediately.",
    avoidsTherapeuticClaims: true,
    urgentHelpVisible: true,
  },
  routeGuidance: [
    {
      routeId: "/accessibility",
      title: "Accessibility route guidance",
      message: "Keep support practical, calm, and connected to real student actions.",
      actionLabel: "Open support hub",
      href: "/support",
    },
    {
      routeId: "/support",
      title: "Support route guidance",
      message: "Signpost trusted services and avoid pretending the platform is counselling support.",
      actionLabel: "Open trusted support",
      href: "/support",
    },
    {
      routeId: "/recommendations",
      title: "Recommendations route guidance",
      message: "Recommendations should keep support signals visible when the next step feels heavy.",
      actionLabel: "See recommendations",
      href: "/recommendations",
    },
  ],
  urgentHelp: [
    {
      optionId: "urgent-1",
      name: "Urgent NHS help",
      actionText: "Get urgent help",
      contactLabel: "NHS urgent help",
      url: "https://www.nhs.uk/nhs-services/mental-health-services/where-to-get-urgent-help-for-mental-health/",
      lastReviewedAt: "2026-06-10T09:00:00.000Z",
    },
  ],
  examSupportGuides: [
    {
      guideId: "guide-1",
      title: "Managing exam stress",
      organisation: "YoungMinds",
      url: "https://example.com/exam-stress-guide",
      summary: "Practical guidance for calming the lead-up to timed work.",
      topicsCovered: ["exam stress", "revision routine"],
      lastReviewedAt: "2026-06-10T09:00:00.000Z",
    },
  ],
  trustedResources: [
    {
      resourceId: "resource-1",
      name: "Childline",
      category: "text-support",
      description: "Trusted support for young people when they need to talk.",
      url: "https://www.childline.org.uk/get-support/1-2-1-counsellor-chat/",
      providerType: "registered-charity",
      audience: "young-people",
      urgent: true,
      lastReviewedAt: "2026-06-10T09:00:00.000Z",
    },
  ],
};
